const movies = [
  {
    adult: false,
    backdrop_path: "/kyqM6padQzZ1eYxv84i9smNvZAG.jpg",
    id: 1078605,
    title: "Weapons",
    original_title: "Weapons",
    overview:
      "When all but one child from the same class mysteriously vanish on the same night at exactly the same time, a community is left questioning who or what is behind their disappearance.",
    poster_path: "/cpf7vsRZ0MYRQcnLWteD5jK9ymT.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [27, 9648],
    popularity: 249.1853,
    release_date: "2025-08-06",
    video: false,
    vote_average: 7.72,
    vote_count: 218,
  },
  {
    adult: false,
    backdrop_path: "/zNriRTr0kWwyaXPzdg1EIxf0BWk.jpg",
    id: 1234821,
    title: "Jurassic World Rebirth",
    original_title: "Jurassic World Rebirth",
    overview:
      "Five years after the events of Jurassic World Dominion, covert operations expert Zora Bennett is contracted to lead a skilled team on a top-secret mission to secure genetic material from the world's three most massive dinosaurs. When Zora's operation intersects with a civilian family whose boating expedition was capsized, they all find themselves stranded on an island where they come face-to-face with a sinister, shocking discovery that's been hidden from the world for decades.",
    poster_path: "/1RICxzeoNCAO5NpcRMIgg1XT6fm.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [878, 12, 28],
    popularity: 1127.7172,
    release_date: "2025-07-01",
    video: false,
    vote_average: 6.415,
    vote_count: 1397,
  },
  {
    adult: false,
    backdrop_path: "/a6bItEVaxgphpMswho1wVRerv4r.jpg",
    id: 7451,
    title: "xXx",
    original_title: "xXx",
    overview:
      'Xander Cage is your standard adrenaline junkie with no fear and a lousy attitude. When the US Government "recruits" him to go on a mission, he\'s not exactly thrilled. His mission: to gather information on an organization that may just be planning the destruction of the world, led by the nihilistic Yorgi.',
    poster_path: "/xeEw3eLeSFmJgXZzmF2Efww0q3s.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [28, 12, 53, 80],
    popularity: 109.2278,
    release_date: "2002-08-09",
    video: false,
    vote_average: 5.957,
    vote_count: 4502,
  },
  {
    adult: false,
    backdrop_path: "/y7tjLYcq2ZGy2DNG0ODhGX9Tm60.jpg",
    id: 1106289,
    title: "The Pickup",
    original_title: "The Pickup",
    overview:
      "A routine cash pickup takes a wild turn when mismatched armored truck drivers Russell and Travis are ambushed by ruthless criminals led by savvy mastermind Zoe.",
    poster_path: "/vFWvWhfAvij8UIngg2Vf6JV95Cr.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [28, 35, 80],
    popularity: 517.1636,
    release_date: "2025-07-27",
    video: false,
    vote_average: 6.598,
    vote_count: 188,
  },
  {
    adult: false,
    backdrop_path: "/zav0v7gLWMu6pVwgsIAwt11GJ4C.jpg",
    id: 1100988,
    title: "28 Years Later",
    original_title: "28 Years Later",
    overview:
      "Twenty-eight years since the rage virus escaped a biological weapons laboratory, now, still in a ruthlessly enforced quarantine, some have found ways to exist amidst the infected. One such group lives on a small island connected to the mainland by a single, heavily-defended causeway. When one member departs on a mission into the dark heart of the mainland, he discovers secrets, wonders, and horrors that have mutated not only the infected but other survivors as well.",
    poster_path: "/mIg1qCkVxnAlM2TK3RUF0tdEXlE.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [27, 53, 878],
    popularity: 254.6574,
    release_date: "2025-06-18",
    video: false,
    vote_average: 6.864,
    vote_count: 1055,
  },
  {
    adult: false,
    backdrop_path: "/eU7IfdWq8KQy0oNd4kKXS0QUR08.jpg",
    id: 1061474,
    title: "Superman",
    original_title: "Superman",
    overview:
      "Superman, a journalist in Metropolis, embarks on a journey to reconcile his Kryptonian heritage with his human upbringing as Clark Kent.",
    poster_path: "/ombsmhYUqR4qqOLOxAyr5V8hbyv.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [878, 12, 28],
    popularity: 199.5313,
    release_date: "2025-07-09",
    video: false,
    vote_average: 7.68,
    vote_count: 1646,
  },
  {
    adult: false,
    backdrop_path: "/mrKpSRMvbZUa9Uwseq63e9Wl7PC.jpg",
    id: 1020047,
    title: "In the Hand of Dante",
    original_title: "In the Hand of Dante",
    overview:
      "When the original manuscript of The Divine Comedy emerges in the clutches of a black-market smuggling ring in New York City's dangerous underbelly, the mob calls weary scholar Nick to authenticate it. Overwhelmed by temptation, Nick defies the mafia and steals the manuscript. As he follows a dark and violent path from a metaphorical Hell into Paradise with his love Giulietta, a parallel tale unfolds: the odyssey of Dante himself, a man who, trapped in a loveless marriage with Gemma and bolstered only by his mentorship under an austere intellectual, escapes to Sicily and creates his masterpiece.",
    poster_path: "/qBouNZBszGuXUBtvsp7tnWceleg.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [80, 18],
    popularity: 3.6692,
    release_date: "2025-09-03",
    video: false,
    vote_average: 0.0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/s94NjfKkcSczZ1FembwmQZwsuwY.jpg",
    id: 617126,
    title: "The Fantastic 4: First Steps",
    original_title: "The Fantastic 4: First Steps",
    overview:
      "Against the vibrant backdrop of a 1960s-inspired, retro-futuristic world, Marvel's First Family is forced to balance their roles as heroes with the strength of their family bond, while defending Earth from a ravenous space god called Galactus and his enigmatic Herald, Silver Surfer.",
    poster_path: "/x26MtUlwtWD26d0G0FXcppxCJio.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [878, 12],
    popularity: 192.4302,
    release_date: "2025-07-23",
    video: false,
    vote_average: 7.252,
    vote_count: 922,
  },
  {
    adult: false,
    backdrop_path: "/dcLV5rEXuQRW0ZlB7IMLArHMyWh.jpg",
    id: 1125257,
    title: "Freakier Friday",
    original_title: "Freakier Friday",
    overview:
      "Years after Tess and Anna endured an identity crisis, Anna now has a daughter of her own and a soon-to-be stepdaughter. As they navigate the myriad challenges that come when two families merge, Tess and Anna discover lightning might indeed strike twice.",
    poster_path: "/9wV65OmsjLAqBfDnYTkMPutXH8j.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [14, 35, 10751],
    popularity: 86.0138,
    release_date: "2025-08-06",
    video: false,
    vote_average: 7.1,
    vote_count: 51,
  },
  {
    adult: false,
    backdrop_path: "/cEQMqB3ahd4mfeUN6VGC0ouVnZZ.jpg",
    id: 1071585,
    title: "M3GAN 2.0",
    original_title: "M3GAN 2.0",
    overview:
      "After the underlying tech for M3GAN is stolen and misused by a powerful defense contractor to create a military-grade weapon known as Amelia, M3GAN's creator Gemma realizes that the only option is to resurrect M3GAN and give her a few upgrades, making her faster, stronger, and more lethal.",
    poster_path: "/4a63rQqIDTrYNdcnTXdPsQyxVLo.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [28, 878, 53],
    popularity: 240.5492,
    release_date: "2025-06-25",
    video: false,
    vote_average: 7.599,
    vote_count: 665,
  },
  {
    adult: false,
    backdrop_path: "/dv5Iu1cI6nsxyPfFusEYbeRkrIJ.jpg",
    id: 1035259,
    title: "The Naked Gun",
    original_title: "The Naked Gun",
    overview:
      "Only one man has the particular set of skills... to lead Police Squad and save the world: Lt. Frank Drebin Jr.",
    poster_path: "/rmwQ8GsdQ1M3LtemNWLErle2nBU.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [35, 80],
    popularity: 67.2147,
    release_date: "2025-07-30",
    video: false,
    vote_average: 7.0,
    vote_count: 149,
  },
  {
    adult: false,
    backdrop_path: "/u2ctOiURF9hL3hmXmEMHxcVPVrQ.jpg",
    id: 1242011,
    title: "Together",
    original_title: "Together",
    overview:
      "With a move to the countryside already testing the limits of a couple's relationship, a supernatural encounter begins an extreme transformation of their love, their lives, and their flesh.",
    poster_path: "/inliWt3ukcpKDGPpEe2lRDLwK2r.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [27],
    popularity: 82.7075,
    release_date: "2025-07-28",
    video: false,
    vote_average: 7.4,
    vote_count: 128,
  },
  {
    adult: false,
    backdrop_path: "/wO15XEgeLbeijtf3MQAUqWCxSxc.jpg",
    id: 1007734,
    title: "Nobody 2",
    original_title: "Nobody 2",
    overview:
      "Former assassin Hutch Mansell takes his family on a nostalgic vacation to a small-town theme park, only to be pulled back into violence when they clash with a corrupt operator, a crooked sheriff, and a ruthless crime boss.",
    poster_path: "/iyxwxDZCpIm0vIORaHpmgJv2BGF.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [28, 53, 80],
    popularity: 14.001,
    release_date: "2025-08-13",
    video: false,
    vote_average: 8.25,
    vote_count: 4,
  },
  {
    adult: false,
    backdrop_path: "/lecBUG6Hsw7pYjTNAPBUgouDfjW.jpg",
    id: 842924,
    title: "The Life of Chuck",
    original_title: "The Life of Chuck",
    overview:
      "In this extraordinary story of an ordinary man, Charles 'Chuck' Krantz experiences the wonder of love, the heartbreak of loss, and the multitudes contained in all of us.",
    poster_path: "/oumprkO9bThExP8NwxBIBnvBu2v.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [878, 14, 18],
    popularity: 25.1303,
    release_date: "2025-06-05",
    video: false,
    vote_average: 7.351,
    vote_count: 212,
  },
  {
    adult: false,
    backdrop_path: "/rthMuZfFv4fqEU4JVbgSW9wQ8rs.jpg",
    id: 986056,
    title: "Thunderbolts*",
    original_title: "Thunderbolts*",
    overview:
      "After finding themselves ensnared in a death trap, seven disillusioned castoffs must embark on a dangerous mission that will force them to confront the darkest corners of their pasts.",
    poster_path: "/hqcexYHbiTBfDIdDWxrxPtVndBX.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [28, 878, 12],
    popularity: 120.129,
    release_date: "2025-04-30",
    video: false,
    vote_average: 7.404,
    vote_count: 2175,
  },
  {
    adult: false,
    backdrop_path: "/c9xmB53umjnrCMS4pZz11clF3yJ.jpg",
    id: 980477,
    title: "Ne Zha 2",
    original_title: "哪吒之魔童闹海",
    overview:
      "After a catastrophic event leaves their bodies destroyed, Ne Zha and Ao Bing are granted a fragile second chance at life. As tensions rise between the dragon clans and celestial forces, the two must undergo a series of perilous trials that will test their bond, challenge their identities, and decide the fate of both mortals and immortals.",
    poster_path: "/293Mo4GWf7Tl0TfAr5NFghqeMy7.jpg",
    media_type: "movie",
    original_language: "zh",
    genre_ids: [16, 14, 12, 28],
    popularity: 274.277,
    release_date: "2025-01-29",
    video: false,
    vote_average: 8.03,
    vote_count: 263,
  },
  {
    adult: false,
    backdrop_path: "/xGu5jTd34DjXGwS7JLmDbgvIQ1U.jpg",
    id: 755898,
    title: "War of the Worlds",
    original_title: "War of the Worlds",
    overview:
      "Will Radford is a top analyst for Homeland Security who tracks potential threats through a mass surveillance program, until one day an attack by an unknown entity leads him to question whether the government is hiding something from him... and from the rest of the world.",
    poster_path: "/yvirUYrva23IudARHn3mMGVxWqM.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [878, 53],
    popularity: 1820.7774,
    release_date: "2025-07-29",
    video: false,
    vote_average: 4.343,
    vote_count: 271,
  },
  {
    adult: false,
    backdrop_path: "/lqwwGkwJHtz9QgKtz4zeY19YgDg.jpg",
    id: 1136867,
    title: "Materialists",
    original_title: "Materialists",
    overview:
      "A young, ambitious New York City matchmaker finds herself torn between the perfect match and her imperfect ex.",
    poster_path: "/eDo0pNruy0Qgj6BdTyHIR4cxHY8.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [10749, 18],
    popularity: 65.8283,
    release_date: "2025-06-12",
    video: false,
    vote_average: 6.737,
    vote_count: 302,
  },
  {
    adult: false,
    backdrop_path: "/AeDzjt00Hfh9CuW7TIUdYBJmWYM.jpg",
    id: 1087192,
    title: "How to Train Your Dragon",
    original_title: "How to Train Your Dragon",
    overview:
      "On the rugged isle of Berk, where Vikings and dragons have been bitter enemies for generations, Hiccup stands apart, defying centuries of tradition when he befriends Toothless, a feared Night Fury dragon. Their unlikely bond reveals the true nature of dragons, challenging the very foundations of Viking society.",
    poster_path: "/q5pXRYTycaeW6dEgsCrd4mYPmxM.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [14, 10751, 28, 12],
    popularity: 395.2745,
    release_date: "2025-06-06",
    video: false,
    vote_average: 8.025,
    vote_count: 1546,
  },
  {
    adult: false,
    backdrop_path: "/uIpJPDNFoeX0TVml9smPrs9KUVx.jpg",
    id: 574475,
    title: "Final Destination Bloodlines",
    original_title: "Final Destination Bloodlines",
    overview:
      "Plagued by a violent recurring nightmare, college student Stefanie heads home to track down the one person who might be able to break the cycle and save her family from the grisly demise that inevitably awaits them all.",
    poster_path: "/6WxhEvFsauuACfv8HyoVX6mZKFj.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [27, 9648],
    popularity: 125.8909,
    release_date: "2025-05-14",
    video: false,
    vote_average: 7.169,
    vote_count: 1911,
  },
];

export default movies;
