const movies = [
  {
    adult: false,
    backdrop_path: "/Q2OajDi2kcO6yErb1IAyVDTKMs.jpg",
    id: 1078605,
    title: "Weapons",
    original_title: "Weapons",
    overview:
      "When all but one child from the same class mysteriously vanish on the same night at exactly the same time, a community is left questioning who or what is behind their disappearance.",
    poster_path: "/cpf7vsRZ0MYRQcnLWteD5jK9ymT.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [27, 9648],
    popularity: 264.6392,
    release_date: "2025-08-06",
    video: false,
    vote_average: 7.8,
    vote_count: 227,
  },
  {
    adult: false,
    backdrop_path: "/qg8Gv2w0dDL8cMsG2QO2hWp58wy.jpg",
    id: 119051,
    name: "Wednesday",
    original_name: "Wednesday",
    overview:
      "Smart, sarcastic and a little dead inside, Wednesday Addams investigates twisted mysteries while making new friends — and foes — at Nevermore Academy.",
    poster_path: "/36xXlhEpQqVVPuiZhfoQuaY4OlA.jpg",
    media_type: "tv",
    original_language: "en",
    genre_ids: [10765, 9648, 35],
    popularity: 899.7084,
    first_air_date: "2022-11-23",
    vote_average: 8.408,
    vote_count: 9350,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/zNriRTr0kWwyaXPzdg1EIxf0BWk.jpg",
    id: 1234821,
    title: "Jurassic World Rebirth",
    original_title: "Jurassic World Rebirth",
    overview:
      "Five years after the events of Jurassic World Dominion, covert operations expert Zora Bennett is contracted to lead a skilled team on a top-secret mission to secure genetic material from the world's three most massive dinosaurs. When Zora's operation intersects with a civilian family whose boating expedition was capsized, they all find themselves stranded on an island where they come face-to-face with a sinister, shocking discovery that's been hidden from the world for decades.",
    poster_path: "/1RICxzeoNCAO5NpcRMIgg1XT6fm.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [878, 12, 28],
    popularity: 1274.2264,
    release_date: "2025-07-01",
    video: false,
    vote_average: 6.415,
    vote_count: 1409,
  },
  {
    adult: false,
    backdrop_path: "/y7tjLYcq2ZGy2DNG0ODhGX9Tm60.jpg",
    id: 1106289,
    title: "The Pickup",
    original_title: "The Pickup",
    overview:
      "A routine cash pickup takes a wild turn when mismatched armored truck drivers Russell and Travis are ambushed by ruthless criminals led by savvy mastermind Zoe.",
    poster_path: "/vFWvWhfAvij8UIngg2Vf6JV95Cr.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [28, 35, 80],
    popularity: 525.8232,
    release_date: "2025-07-27",
    video: false,
    vote_average: 6.592,
    vote_count: 190,
  },
  {
    adult: false,
    backdrop_path: "/25g7mthXoJFcNZhAKz0evk17Bsx.jpg",
    id: 157239,
    name: "Alien: Earth",
    original_name: "Alien: Earth",
    overview:
      "When the mysterious deep space research vessel USCSS Maginot crash-lands on Earth, Wendy and a ragtag group of tactical soldiers make a fateful discovery that puts them face-to-face with the planet's greatest threat.",
    poster_path: "/o7IrqyqMZQQDH5AJmoFMjsNLkqn.jpg",
    media_type: "tv",
    original_language: "en",
    genre_ids: [18, 10765],
    popularity: 41.885,
    first_air_date: "2025-08-12",
    vote_average: 9.0,
    vote_count: 10,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/x87BVYT8JBMyWjFnhcjdY7fy4Nt.jpg",
    id: 207484,
    name: "Outlander: Blood of My Blood",
    original_name: "Outlander: Blood of My Blood",
    overview:
      "From the battlefields of World War I to the rugged Highlands of 18th century Scotland, two fated couples must defy the forces that seek to tear them apart, unfolding in surprising and unforeseen ways in this romantic saga that unfolds across time.",
    poster_path: "/hlwZbEKXLbZvgdfxCT1j54pRyE4.jpg",
    media_type: "tv",
    original_language: "en",
    genre_ids: [18],
    popularity: 101.6067,
    first_air_date: "2025-08-08",
    vote_average: 8.9,
    vote_count: 13,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/dcLV5rEXuQRW0ZlB7IMLArHMyWh.jpg",
    id: 1125257,
    title: "Freakier Friday",
    original_title: "Freakier Friday",
    overview:
      "Years after Tess and Anna endured an identity crisis, Anna now has a daughter of her own and a soon-to-be stepdaughter. As they navigate the myriad challenges that come when two families merge, Tess and Anna discover lightning might indeed strike twice.",
    poster_path: "/9wV65OmsjLAqBfDnYTkMPutXH8j.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [14, 35, 10751],
    popularity: 90.9967,
    release_date: "2025-08-06",
    video: false,
    vote_average: 7.2,
    vote_count: 52,
  },
  {
    adult: false,
    backdrop_path: "/eU7IfdWq8KQy0oNd4kKXS0QUR08.jpg",
    id: 1061474,
    title: "Superman",
    original_title: "Superman",
    overview:
      "Superman, a journalist in Metropolis, embarks on a journey to reconcile his Kryptonian heritage with his human upbringing as Clark Kent.",
    poster_path: "/ombsmhYUqR4qqOLOxAyr5V8hbyv.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [878, 12, 28],
    popularity: 186.4536,
    release_date: "2025-07-09",
    video: false,
    vote_average: 7.679,
    vote_count: 1650,
  },
  {
    adult: false,
    backdrop_path: "/jPcQlhoJ3LrOfKwCvGD58P8rC5b.jpg",
    id: 81723,
    name: "The Gilded Age",
    original_name: "The Gilded Age",
    overview:
      "It’s 1882 and the Gilded Age is in full swing when Marian Brook, a young orphaned daughter of a Southern general, moves in with her rigidly conventional aunts in New York City. With the help of Peggy Scott, an African-American woman masquerading as her maid, Marian gets caught up in the dazzling lives of her rich neighbors as she struggles to decide between adhering to the rules or forging her own path.",
    poster_path: "/4zXlBCc1rNTDtrfMCBFIGKWlwnC.jpg",
    media_type: "tv",
    original_language: "en",
    genre_ids: [18],
    popularity: 29.4618,
    first_air_date: "2022-01-24",
    vote_average: 7.66,
    vote_count: 216,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/6fRwRD7GdCfg6owzmCT3VgQtowl.jpg",
    id: 37854,
    name: "One Piece",
    original_name: "ワンピース",
    overview:
      'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
    poster_path: "/cMD9Ygz11zjJzAovURpO75Qg7rT.jpg",
    media_type: "tv",
    original_language: "ja",
    genre_ids: [10759, 35, 16],
    popularity: 26.2753,
    first_air_date: "1999-10-20",
    vote_average: 8.724,
    vote_count: 4958,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/s94NjfKkcSczZ1FembwmQZwsuwY.jpg",
    id: 617126,
    title: "The Fantastic 4: First Steps",
    original_title: "The Fantastic 4: First Steps",
    overview:
      "Against the vibrant backdrop of a 1960s-inspired, retro-futuristic world, Marvel's First Family is forced to balance their roles as heroes with the strength of their family bond, while defending Earth from a ravenous space god called Galactus and his enigmatic Herald, Silver Surfer.",
    poster_path: "/x26MtUlwtWD26d0G0FXcppxCJio.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [878, 12],
    popularity: 180.5792,
    release_date: "2025-07-23",
    video: false,
    vote_average: 7.251,
    vote_count: 927,
  },
  {
    adult: false,
    backdrop_path: "/c9xmB53umjnrCMS4pZz11clF3yJ.jpg",
    id: 980477,
    title: "Ne Zha 2",
    original_title: "哪吒之魔童闹海",
    overview:
      "After a catastrophic event leaves their bodies destroyed, Ne Zha and Ao Bing are granted a fragile second chance at life. As tensions rise between the dragon clans and celestial forces, the two must undergo a series of perilous trials that will test their bond, challenge their identities, and decide the fate of both mortals and immortals.",
    poster_path: "/293Mo4GWf7Tl0TfAr5NFghqeMy7.jpg",
    media_type: "movie",
    original_language: "zh",
    genre_ids: [16, 14, 12, 28],
    popularity: 255.393,
    release_date: "2025-01-29",
    video: false,
    vote_average: 8.023,
    vote_count: 264,
  },
  {
    adult: false,
    backdrop_path: "/u2ctOiURF9hL3hmXmEMHxcVPVrQ.jpg",
    id: 1242011,
    title: "Together",
    original_title: "Together",
    overview:
      "With a move to the countryside already testing the limits of a couple's relationship, a supernatural encounter begins an extreme transformation of their love, their lives, and their flesh.",
    poster_path: "/inliWt3ukcpKDGPpEe2lRDLwK2r.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [27],
    popularity: 69.6668,
    release_date: "2025-07-28",
    video: false,
    vote_average: 7.4,
    vote_count: 129,
  },
  {
    adult: false,
    backdrop_path: "/AeDzjt00Hfh9CuW7TIUdYBJmWYM.jpg",
    id: 1087192,
    title: "How to Train Your Dragon",
    original_title: "How to Train Your Dragon",
    overview:
      "On the rugged isle of Berk, where Vikings and dragons have been bitter enemies for generations, Hiccup stands apart, defying centuries of tradition when he befriends Toothless, a feared Night Fury dragon. Their unlikely bond reveals the true nature of dragons, challenging the very foundations of Viking society.",
    poster_path: "/q5pXRYTycaeW6dEgsCrd4mYPmxM.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [14, 10751, 28, 12],
    popularity: 379.0512,
    release_date: "2025-06-06",
    video: false,
    vote_average: 8.022,
    vote_count: 1551,
  },
  {
    adult: false,
    backdrop_path: "/9q7uryMCmAun2bGXoP3Liw24mpz.jpg",
    id: 296834,
    name: "Duel on Mount Hua",
    original_name: "华山论剑",
    overview:
      "«Jin Yong Wuxia Universe» (金庸武侠世界 / The Legend of Heroes) is a martial arts series based on the novels of Jin Yong, with «The Legend of the Condor Heroes» as its main plotline. The series weaves together two dramatic stories – «Hot Blooded» (30 episodes) and «Duel on Mount Hua» (30 episodes), the latter encompassing four character arcs: «Nine Yin True Sutra» (8 episodes), «Eastern Heretic and Western Venom» (8 episodes), «Southern Emperor and Northern Beggar» (8 episodes), and «Five Great Masters» (6 episodes).",
    poster_path: "/3Ja34PSTGolQdZnyAp7R2odiwe7.jpg",
    media_type: "tv",
    original_language: "zh",
    genre_ids: [10759, 18],
    popularity: 55.9136,
    first_air_date: "2025-07-26",
    vote_average: 6.875,
    vote_count: 8,
    origin_country: ["CN"],
  },
  {
    adult: false,
    backdrop_path: "/zav0v7gLWMu6pVwgsIAwt11GJ4C.jpg",
    id: 1100988,
    title: "28 Years Later",
    original_title: "28 Years Later",
    overview:
      "Twenty-eight years since the rage virus escaped a biological weapons laboratory, now, still in a ruthlessly enforced quarantine, some have found ways to exist amidst the infected. One such group lives on a small island connected to the mainland by a single, heavily-defended causeway. When one member departs on a mission into the dark heart of the mainland, he discovers secrets, wonders, and horrors that have mutated not only the infected but other survivors as well.",
    poster_path: "/mIg1qCkVxnAlM2TK3RUF0tdEXlE.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [27, 53, 878],
    popularity: 218.1212,
    release_date: "2025-06-18",
    video: false,
    vote_average: 6.864,
    vote_count: 1059,
  },
  {
    adult: false,
    backdrop_path: "/mrKpSRMvbZUa9Uwseq63e9Wl7PC.jpg",
    id: 1020047,
    title: "In the Hand of Dante",
    original_title: "In the Hand of Dante",
    overview:
      "When the original manuscript of The Divine Comedy emerges in the clutches of a black-market smuggling ring in New York City's dangerous underbelly, the mob calls weary scholar Nick to authenticate it. Overwhelmed by temptation, Nick defies the mafia and steals the manuscript. As he follows a dark and violent path from a metaphorical Hell into Paradise with his love Giulietta, a parallel tale unfolds: the odyssey of Dante himself, a man who, trapped in a loveless marriage with Gemma and bolstered only by his mentorship under an austere intellectual, escapes to Sicily and creates his masterpiece.",
    poster_path: "/qBouNZBszGuXUBtvsp7tnWceleg.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [80, 18],
    popularity: 11.497,
    release_date: "2025-09-03",
    video: false,
    vote_average: 0.0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/dv5Iu1cI6nsxyPfFusEYbeRkrIJ.jpg",
    id: 1035259,
    title: "The Naked Gun",
    original_title: "The Naked Gun",
    overview:
      "Only one man has the particular set of skills... to lead Police Squad and save the world: Lt. Frank Drebin Jr.",
    poster_path: "/rmwQ8GsdQ1M3LtemNWLErle2nBU.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [35, 80],
    popularity: 60.6815,
    release_date: "2025-07-30",
    video: false,
    vote_average: 7.0,
    vote_count: 149,
  },
  {
    adult: false,
    backdrop_path: "/xGu5jTd34DjXGwS7JLmDbgvIQ1U.jpg",
    id: 755898,
    title: "War of the Worlds",
    original_title: "War of the Worlds",
    overview:
      "Will Radford is a top analyst for Homeland Security who tracks potential threats through a mass surveillance program, until one day an attack by an unknown entity leads him to question whether the government is hiding something from him... and from the rest of the world.",
    poster_path: "/yvirUYrva23IudARHn3mMGVxWqM.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [878, 53],
    popularity: 1692.2043,
    release_date: "2025-07-29",
    video: false,
    vote_average: 4.338,
    vote_count: 272,
  },
  {
    adult: false,
    backdrop_path: "/a6bItEVaxgphpMswho1wVRerv4r.jpg",
    id: 7451,
    title: "xXx",
    original_title: "xXx",
    overview:
      'Xander Cage is your standard adrenaline junkie with no fear and a lousy attitude. When the US Government "recruits" him to go on a mission, he\'s not exactly thrilled. His mission: to gather information on an organization that may just be planning the destruction of the world, led by the nihilistic Yorgi.',
    poster_path: "/xeEw3eLeSFmJgXZzmF2Efww0q3s.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [28, 12, 53, 80],
    popularity: 106.2781,
    release_date: "2002-08-09",
    video: false,
    vote_average: 5.957,
    vote_count: 4504,
  },
];

export default movies;
